[package]
name = "remote-mouse"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tungstenite = "0.27.0"
mouce = "0.3.0"